#############################################################################
# Makefile for building: quadtree
# Generated by qmake (2.01a) (Qt 4.7.1) on: Tue Feb 22 16:36:06 2011
# Project:  quadtree.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile quadtree.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtOpenGL -I/usr/include -I. -I/usr/X11R6/include -I.tmp/moc -I.tmp/UISrc
LINK          = g++
LFLAGS        = -m64 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/X11R6/lib64 -L/usr/lib -lIL -lGLU -lGL -lQtOpenGL -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .tmp/objs/

####### Files

SOURCES       = Source/CMath.cpp \
		Source/mainWindow.cpp \
		Source/quadtreeTest.cpp \
		Source/mainApp.cpp \
		Source/CImage.cpp \
		Source/CBalls.cpp \
		Source/CQuadtree.cpp .tmp/moc/moc_CBaseQGL.cpp \
		.tmp/moc/moc_quadtreeTest.cpp \
		.tmp/moc/moc_mainWindow.cpp
OBJECTS       = .tmp/objs/CMath.o \
		.tmp/objs/mainWindow.o \
		.tmp/objs/quadtreeTest.o \
		.tmp/objs/mainApp.o \
		.tmp/objs/CImage.o \
		.tmp/objs/CBalls.o \
		.tmp/objs/CQuadtree.o \
		.tmp/objs/moc_CBaseQGL.o \
		.tmp/objs/moc_quadtreeTest.o \
		.tmp/objs/moc_mainWindow.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		quadtree.pro
QMAKE_TARGET  = quadtree
DESTDIR       = 
TARGET        = quadtree

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): .tmp/UISrc/ui_quadtree.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: quadtree.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile quadtree.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/unix/opengl.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile quadtree.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/objs/quadtree1.0.0 || $(MKDIR) .tmp/objs/quadtree1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/objs/quadtree1.0.0/ && $(COPY_FILE) --parents Source/CMath.h Source/CBaseQGL.h Source/COrthoQGL.h Source/CDebug.h Source/quadtreeTest.h Source/mainWindow.h Source/CImage.h Source/CBalls.h Source/CQuadtree.h .tmp/objs/quadtree1.0.0/ && $(COPY_FILE) --parents Source/CMath.cpp Source/mainWindow.cpp Source/quadtreeTest.cpp Source/mainApp.cpp Source/CImage.cpp Source/CBalls.cpp Source/CQuadtree.cpp .tmp/objs/quadtree1.0.0/ && $(COPY_FILE) --parents Source/quadtree.ui .tmp/objs/quadtree1.0.0/ && (cd `dirname .tmp/objs/quadtree1.0.0` && $(TAR) quadtree1.0.0.tar quadtree1.0.0 && $(COMPRESS) quadtree1.0.0.tar) && $(MOVE) `dirname .tmp/objs/quadtree1.0.0`/quadtree1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/objs/quadtree1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .tmp/moc/moc_CBaseQGL.cpp .tmp/moc/moc_quadtreeTest.cpp .tmp/moc/moc_mainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .tmp/moc/moc_CBaseQGL.cpp .tmp/moc/moc_quadtreeTest.cpp .tmp/moc/moc_mainWindow.cpp
.tmp/moc/moc_CBaseQGL.cpp: Source/CBaseQGL.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Source/CBaseQGL.h -o .tmp/moc/moc_CBaseQGL.cpp

.tmp/moc/moc_quadtreeTest.cpp: Source/COrthoQGL.h \
		Source/CBaseQGL.h \
		Source/CDebug.h \
		Source/CBalls.h \
		Source/CMath.h \
		Source/CQuadtree.h \
		Source/quadtreeTest.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Source/quadtreeTest.h -o .tmp/moc/moc_quadtreeTest.cpp

.tmp/moc/moc_mainWindow.cpp: .tmp/UISrc/ui_quadtree.h \
		Source/quadtreeTest.h \
		Source/COrthoQGL.h \
		Source/CBaseQGL.h \
		Source/CDebug.h \
		Source/CBalls.h \
		Source/CMath.h \
		Source/CQuadtree.h \
		Source/mainWindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Source/mainWindow.h -o .tmp/moc/moc_mainWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: .tmp/UISrc/ui_quadtree.h
compiler_uic_clean:
	-$(DEL_FILE) .tmp/UISrc/ui_quadtree.h
.tmp/UISrc/ui_quadtree.h: Source/quadtree.ui
	/usr/bin/uic Source/quadtree.ui -o .tmp/UISrc/ui_quadtree.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

.tmp/objs/CMath.o: Source/CMath.cpp Source/CMath.h \
		Source/CDebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/objs/CMath.o Source/CMath.cpp

.tmp/objs/mainWindow.o: Source/mainWindow.cpp Source/mainWindow.h \
		.tmp/UISrc/ui_quadtree.h \
		Source/quadtreeTest.h \
		Source/COrthoQGL.h \
		Source/CBaseQGL.h \
		Source/CDebug.h \
		Source/CBalls.h \
		Source/CMath.h \
		Source/CQuadtree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/objs/mainWindow.o Source/mainWindow.cpp

.tmp/objs/quadtreeTest.o: Source/quadtreeTest.cpp Source/quadtreeTest.h \
		Source/COrthoQGL.h \
		Source/CBaseQGL.h \
		Source/CDebug.h \
		Source/CBalls.h \
		Source/CMath.h \
		Source/CQuadtree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/objs/quadtreeTest.o Source/quadtreeTest.cpp

.tmp/objs/mainApp.o: Source/mainApp.cpp Source/mainWindow.h \
		.tmp/UISrc/ui_quadtree.h \
		Source/quadtreeTest.h \
		Source/COrthoQGL.h \
		Source/CBaseQGL.h \
		Source/CDebug.h \
		Source/CBalls.h \
		Source/CMath.h \
		Source/CQuadtree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/objs/mainApp.o Source/mainApp.cpp

.tmp/objs/CImage.o: Source/CImage.cpp Source/CImage.h \
		Source/CDebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/objs/CImage.o Source/CImage.cpp

.tmp/objs/CBalls.o: Source/CBalls.cpp Source/CImage.h \
		Source/CBalls.h \
		Source/CMath.h \
		Source/CDebug.h \
		Source/CQuadtree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/objs/CBalls.o Source/CBalls.cpp

.tmp/objs/CQuadtree.o: Source/CQuadtree.cpp Source/CQuadtree.h \
		Source/CMath.h \
		Source/CDebug.h \
		Source/CBalls.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/objs/CQuadtree.o Source/CQuadtree.cpp

.tmp/objs/moc_CBaseQGL.o: .tmp/moc/moc_CBaseQGL.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/objs/moc_CBaseQGL.o .tmp/moc/moc_CBaseQGL.cpp

.tmp/objs/moc_quadtreeTest.o: .tmp/moc/moc_quadtreeTest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/objs/moc_quadtreeTest.o .tmp/moc/moc_quadtreeTest.cpp

.tmp/objs/moc_mainWindow.o: .tmp/moc/moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/objs/moc_mainWindow.o .tmp/moc/moc_mainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

